### ISSUE TITLE
Update of the pybullet dependency in the drl Conda environment

### ISSUE THREAD

**Issue by robotcopper** [cjlux/DRL_at_ENSEIRB-MATMECA#1]
#### Description

The `drl` Conda environment has been updated to use a new version of the `pybullet` dependency. The previous configuration referred to version 3.25 of `pybullet` via the `conda-forge` channel, but it has now been replaced with version 3.2.5 installed via `pip`.

#### Previous Configuration

```yaml
name: drl
channels:
  - defaults
dependencies:
  - python=3.10
  - conda-forge::pybullet=3.25
  - pytorch=2.0.1
  - tensorboard
  - matplotlib
  - jupyter
  - notebook
  - pip
  - pip:
    - opencv-python-headless
    - gymnasium[all]
    - stable-baselines3==2.1.0
    - moviepy
```

#### New Configuration

```yaml
name: drl
channels:
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - tensorboard
  - matplotlib
  - jupyter
  - notebook
  - pip
  - pip:
    - opencv-python-headless
    - gymnasium[all]
    - stable-baselines3==2.1.0
    - moviepy
    - pybullet==3.2.5
    - pybind11
```

#### Reason for the Update

The update from `pybullet` version 3.25 to version 3.2.5 via `pip` simplifies dependency management, particularly by avoiding the use of the `conda-forge` channel for this specific dependency. Additionally, the `pybullet` version 3.2.5 is better suited for the current environment and compatibility with other libraries in use.

#### Impact

This update ensures better version consistency and prevents potential dependency conflicts. Users should now install `pybullet` directly via `pip` to avoid issues with the previous version via Conda.

#### Actions Required

1. Update the Conda environment with the new YAML configuration.
2. Ensure that users install `pybullet==3.2.5` via `pip` to avoid conflicts.
